functionality:
  name: replace
  description: Search for a substring in a string and replace it with another string
  namespace: string_manipulation
  arguments:
  - type: string
    name: --text
    default: "Hello world!"
  - type: string
    name: --search
    default: "Hello"
  - type: string
    name: --replace
    default: "Greetings"
  resources:
  - type: bash_script
    path: script.sh
  tests:
  - type: bash_script
    path: test.sh
platforms:
  - type: native