data:
- description: An argument of the `boolean_false` type acts like an inverted `boolean`
    flag with a default value of `true`. When called as an argument it sets the `boolean`
    to `false`.
  example:
  - example: "arguments:\n  - name: --no-log\n    type: boolean_false\n    description:\
      \ Disable logging\n    alternatives: [\"-nl\"]\n"
    format: yaml
  hierarchy:
  - io.viash.functionality.arguments.BooleanFalseArgument
  - io.viash.functionality.arguments.BooleanArgumentBase
  - io.viash.functionality.arguments.Argument
  name: __this__
  type: BooleanFalseArgument
- description: List of alternative format variations for this argument.
  name: alternatives
  type: OneOrMore of String
- description: "The name of the argument. Can be in the formats `--no-log`, `-n` or\
    \ `no-log`. The number of dashes determines how values can be passed:  \n\n  -\
    \ `--no-log` is a long option, which can be passed with `executable_name --no-log`\n\
    \  - `-n` is a short option, which can be passed with `executable_name -n`\n \
    \ - `no-log` is an argument, which can be passed with `executable_name no-log`\
    \  \n"
  name: name
  type: String
- description: 'Structured information. Can be any shape: a string, vector, map or
    even nested map.'
  example:
  - example: "info:\n  category: cat1\n  labels: [one, two, three]"
    format: yaml
  name: info
  since: Viash 0.6.3
  type: Json
- description: A description of the argument. This will be displayed with `--help`.
  name: description
  type: Option of String
- description: Specifies the type of the argument.
  name: type
  type: String
title: boolean_false
topic: arguments
