data:
- description: "For each argument, a type and a name must be specified. Depending\
    \ on the type of argument, different properties can be set. See these reference\
    \ pages per type for more information:  \n\n - [string](/reference/config/functionality/arguments/string.html)\n\
    \ - [file](/reference/config/functionality/arguments/file.html)\n - [integer](/reference/config/functionality/arguments/integer.html)\n\
    \ - [double](/reference/config/functionality/arguments/double.html)\n - [boolean](/reference/config/functionality/arguments/boolean.html)\n\
    \ - [boolean_true](/reference/config/functionality/arguments/boolean_true.html)\n\
    \ - [boolean_false](/reference/config/functionality/arguments/boolean_false.html)\n"
  example:
  - example: "arguments:\n   - name: --foo\n    type: file\n    alternatives: [-f]\n\
      \    description: Description of foo\n    default: \"/foo/bar\"\n    must_exist:\
      \ true\n    direction: output\n    required: false\n    multiple: true\n   \
      \ multiple_sep: \",\"\n   - name: --bar\n    type: string\n"
    format: yaml
  hierarchy:
  - io.viash.functionality.arguments.Argument
  name: __this__
  type: Argument
title: argument
topic: arguments
