functionality:
  name: combine_columns
  namespace: example
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      multiple: true
      required: true
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      required: true
      direction: output
    - type: string
      name: --id
      default: "combine_columns"
  resources:
    - type: r_script
      path: ./script.R
platforms:
  - type: docker
    image: rocker/r-ver:4.1
  - type: nextflow
    variant: vdsl3