functionality:
  name: hello_viash
  description: A minimal example component.
  arguments:
  - type: string
    name: --input
    default: "Viash"
  resources:
  - type: bash_script
    path: script.sh
platforms:
  - type: native
  - type: docker
    image: bash:4.0