project:
  type: website
  output-dir: _site
  preview:
    port: 8000
    browser: false
  resources:
    - "/_redirects"

website:
  title: "Viash"
  image: "viash.png"
  favicon: "favicon.png"
  google-analytics: "G-GDS2XT0DDG"
  open-graph: true
  twitter-card: true
  site-url: https://viash.io
  repo-url: https://github.com/viash-io/viash_web
  page-navigation: true
  page-footer:
    # left: 
    #   - text: "About"
    #     href: about.qmd
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: documentation/faq/index.qmd
      - text: "Privacy Policy"
        href: privacy.qmd
    right:
      - icon: twitter
        href: https://twitter.com/DataIntuitive
        aria-label: Viash Twitter
      - icon: github
        href: https://github.com/viash-io/viash
        aria-label: Viash GitHub
  navbar:
    background: light
    logo: viash.png
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Installation"
        href: documentation/installation/index.qmd
      - text: "Quickstart"
        href: documentation/quickstart/index.qmd
      - text: "Guide"
        href: documentation/guide/index.qmd
      - text: "Reference"
        href: documentation/reference/index.qmd
      # - text: "Gallery"
      #   href: documentation/gallery/index.qmd
      - text: "Blog"
        href: documentation/blog/index.qmd
      - text: "Help"
        menu:
          # - text: "Terminology"
          #   icon: "journal-text"
          #   href: documentation/help/terminology.qmd
          - text: "Report a Viash issue"
            icon: "bug"
            href: "https://github.com/viash-io/viash/issues"
          - text: "Report a website issue"
            icon: "bug"
            href: "https://github.com/viash-io/website/issues"
    right:
      - icon: twitter
        href: https://twitter.com/DataIntuitive
        aria-label: Viash Twitter
      - icon: github
        href: https://github.com/viash-io/viash
        aria-label: Viash GitHub

  sidebar:
    - id: guide
      # collapse-level: 1
      contents:
        - text: "Guide"
          href: documentation/guide/index.qmd
        - section: "Viash Component"
          contents:
            - section: "Creation"
              contents:
                - documentation/guide/component/creation/native.qmd
                - documentation/guide/component/creation/docker.qmd
                - documentation/guide/component/creation/nextflow.qmd
            - documentation/guide/component/languages.qmd
            - documentation/guide/component/unit-testing.qmd
            - documentation/guide/component/namespaces.qmd
            # - documentation/guide/component/resources.qmd
        - section: "Build Targets"
          contents:
            - documentation/guide/building-block/native-building-running.qmd
            # - documentation/guide/building-block/docker/building-running.qmd
            - section: "Docker Executable"
              contents:
                - documentation/guide/building-block/docker/building-running.qmd
                - documentation/guide/building-block/docker/docker-volume.qmd
                - documentation/guide/building-block/docker/inspect-dockerfile.qmd
                - documentation/guide/building-block/docker/setup-strategies.qmd
            - section: "Nextflow Module"
              contents:
                - documentation/guide/building-block/nextflow/building-running.qmd
        - section: "Data Workflow"
          contents:
            # - documentation/guide/data-workflow/scripted-pipeline.qmd
            - section: "Nextflow Pipeline"
              contents:
                - documentation/guide/data-workflow/nextflow-pipeline/pipeline-basics.qmd
                - documentation/guide/data-workflow/nextflow-pipeline/pipeline-advanced.qmd
        - section: "Development Setup"
          contents:
            - documentation/guide/dev-environment/vscode.qmd
        # - section: "Project"
        #   contents:
        #     - section: "Setup"
        #     - section: "Customizing"
        - documentation/help/terminology.qmd



    - id: reference
      title: "Reference"
      contents:
        - documentation/reference/index.qmd
        - section: "Viash Commands"
          contents:     
            - documentation/reference/viash/build.qmd
            - documentation/reference/viash/config.qmd
            - documentation/reference/viash/ns.qmd
            - documentation/reference/viash/run.qmd
            - documentation/reference/viash/test.qmd
        - section: "Viash Config"
          contents:
            - documentation/reference/config/overview.qmd
            - documentation/reference/config/functionality.qmd
            - section: "Platforms"
              contents:
              - documentation/reference/config/platforms/nativePlatform.qmd
              - documentation/reference/config/platforms/dockerPlatform.qmd
              - documentation/reference/config/platforms/nextflowLegacyPlatform.qmd
              - documentation/reference/config/platforms/nextflowVdsl3Platform.qmd
            - section: "Argument Types"
              contents:
              - documentation/reference/config/arguments/boolean_false.qmd
              - documentation/reference/config/arguments/boolean_true.qmd
              - documentation/reference/config/arguments/boolean.qmd
              - documentation/reference/config/arguments/double.qmd
              - documentation/reference/config/arguments/file.qmd
              - documentation/reference/config/arguments/integer.qmd
              - documentation/reference/config/arguments/string.qmd


format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    link-external-icon: false
    link-external-newwindow: true
    code-copy: true
    code-overflow: scroll
    css: styles.css
    include-after-body: js.html
    mermaid-format: js

freeze: false
