project:
  type: website
  output-dir: _site
  preview:
    port: 8000
    browser: false
  resources:
    - "/_redirects"

website:
  title: "Viash"
  image: "viash.png"
  favicon: "favicon.png"
  google-analytics: "G-GDS2XT0DDG"
  open-graph: true
  twitter-card: true
  site-url: https://viash.io
  repo-url: https://github.com/viash-io/website
  page-navigation: true
  page-footer:
    # left: 
    #   - text: "About"
    #     href: about.qmd
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: faq/index.qmd
      - text: "Privacy Policy"
        href: privacy.qmd
    right:
      - icon: twitter
        href: https://twitter.com/DataIntuitive
        aria-label: Viash Twitter
      - icon: github
        href: https://github.com/viash-io/viash
        aria-label: Viash GitHub
  navbar:
    background: light
    logo: viash.png
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Installation"
        href: installation/index.qmd
      - text: "Quickstart"
        href: quickstart/index.qmd
      - text: "Guide"
        href: guide/index.qmd
      - text: "Guide_v2"
        href: guide_v2/index.qmd
      - text: "Reference"
        href: reference/index.qmd
      # - text: "Gallery"
      #   href: gallery/index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Help"
        menu:
          # - text: "Terminology"
          #   icon: "journal-text"
          #   href: help/terminology.qmd
          - text: "Report a Viash issue"
            icon: "bug"
            href: "https://github.com/viash-io/viash/issues"
          - text: "Report a website issue"
            icon: "bug"
            href: "https://github.com/viash-io/website/issues"
    right:
      - icon: twitter
        href: https://twitter.com/DataIntuitive
        aria-label: Viash Twitter
      - icon: github
        href: https://github.com/viash-io/viash
        aria-label: Viash GitHub

  sidebar:
    - id: guide
      # collapse-level: 1
      contents:
        - text: "Guide"
          href: guide/index.qmd
        - section: "Viash Component"
          contents:
            - section: "Creation"
              contents:
                - guide/component/creation/native.qmd
                - guide/component/creation/docker.qmd
                - guide/component/creation/nextflow.qmd
            - guide/component/languages.qmd
            - guide/component/unit-testing.qmd
            - guide/component/namespaces.qmd
            # - guide/component/resources.qmd
        - section: "Build Targets"
          contents:
            - guide/building-block/native-building-running.qmd
            # - guide/building-block/docker/building-running.qmd
            - section: "Docker Executable"
              contents:
                - guide/building-block/docker/building-running.qmd
                - guide/building-block/docker/docker-volume.qmd
                - guide/building-block/docker/inspect-dockerfile.qmd
                - guide/building-block/docker/setup-strategies.qmd
            - section: "Nextflow Module"
              contents:
                - guide/building-block/nextflow/building-running.qmd
        - section: "Data Workflow"
          contents:
            # - guide/data-workflow/scripted-pipeline.qmd
            - section: "Nextflow Pipeline"
              contents:
                - guide/data-workflow/nextflow-pipeline/pipeline-basics.qmd
                - guide/data-workflow/nextflow-pipeline/pipeline-advanced.qmd
        - section: "Development Setup"
          contents:
            - guide/dev-environment/vscode.qmd
        # - section: "Project"
        #   contents:
        #     - section: "Setup"
        #     - section: "Customizing"
        - help/terminology.qmd

    - id: guide_v2
      # collapse-level: 1
      contents:
        - text: "Guide"
          href: guide_v2/index.qmd
        - section: "Viash Component"
          contents:
            - guide_v2/component/create-component.qmd
            - guide_v2/component/add-dependencies.qmd
            - guide_v2/component/add-resources.qmd
            - guide_v2/component/variables.qmd
            - guide_v2/component/use-helper-functions.qmd
            - guide_v2/component/testing.qmd
            - guide_v2/component/requirements.qmd
        # - section: "Build Targets"
        #   contents:
        #     - guide/building-block/native-building-running.qmd
        #     # - guide/building-block/docker/building-running.qmd
        #     - section: "Docker Executable"
        #       contents:
        #         - guide/building-block/docker/building-running.qmd
        #         - guide/building-block/docker/docker-volume.qmd
        #         - guide/building-block/docker/inspect-dockerfile.qmd
        #         - guide/building-block/docker/setup-strategies.qmd
        #     - section: "Nextflow Module"
        #       contents:
        #         - guide/building-block/nextflow/building-running.qmd
        # - section: "Data Workflow"
        #   contents:
        #     # - guide/data-workflow/scripted-pipeline.qmd
        #     - section: "Nextflow Pipeline"
        #       contents:
        #         - guide/data-workflow/nextflow-pipeline/pipeline-basics.qmd
        #         - guide/data-workflow/nextflow-pipeline/pipeline-advanced.qmd
        # - section: "Development Setup"
        #   contents:
        #     - guide/dev-environment/vscode.qmd
        # # - section: "Project"
        # #   contents:
        # #     - section: "Setup"
        # #     - section: "Customizing"
        # - help/terminology.qmd



    - id: reference
      title: "Reference"
      contents:
        - reference/index.qmd
        - section: "Viash Commands"
          contents:     
            - reference/viash/build.qmd
            - reference/viash/config.qmd
            - reference/viash/ns.qmd
            - reference/viash/run.qmd
            - reference/viash/test.qmd
        - section: "Viash Config"
          contents:
            - reference/config/index.qmd
            - reference/config/functionality.qmd
            - reference/config/config-modding.qmd
            - section: "Platforms"
              contents:
              - reference/config/platforms/NativePlatform.qmd
              - reference/config/platforms/DockerPlatform.qmd
              - reference/config/platforms/NextflowLegacyPlatform.qmd
              - reference/config/platforms/NextflowVdsl3Platform.qmd
            - section: "Argument Types"
              contents:
              - reference/config/arguments/boolean_false.qmd
              - reference/config/arguments/boolean_true.qmd
              - reference/config/arguments/boolean.qmd
              - reference/config/arguments/double.qmd
              - reference/config/arguments/file.qmd
              - reference/config/arguments/integer.qmd
              - reference/config/arguments/string.qmd
            - reference/config/requirements.qmd

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    link-external-icon: false
    link-external-newwindow: true
    code-copy: true
    code-overflow: scroll
    css: styles.css
    include-after-body: js.html
    mermaid-format: js

execute:
  freeze: auto
