project:
  type: website
  output-dir: _site
  preview:
    port: 8000
    browser: false
  resources:
    - "/documentation/download/_download.json"
    - "/_redirects"

website:
  title: "Viash"
  image: "quarto.png"
  favicon: "favicon.png"
  # google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  site-url: https://viash.io
  repo-url: https://github.com/viash-io/viash_web
  # repo-actions: [edit, issue]
  page-navigation: true
  # search:
  #   algolia:
  #     index-name: prod_QUARTO
  #     application-id: ZPJB5I1QN7
  #     search-only-api-key: 41be6c1e0a7fea4a51b107810facf577
  #     analytics-events: true
  #     show-logo: true
  page-footer:
    left: |
      Left footer
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: documentation/faq/index.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
    right:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: Quarto GitHub
  navbar:
    background: light
    logo: quarto.png
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      # - text: "Get Started"
      #   href: documentation/get-started/index.qmd
      - text: "Guide"
        href: documentation/guide/index.qmd
      # - text: "API"
      #   href: documentation/reference/index.qmd
      # - text: "Gallery"
      #   href: documentation/gallery/index.qmd
      # - text: "Blog"
      #   href: documentation/blog/index.qmd
      - text: "Help"
        menu:
          - text: "Report a Viash issue"
            icon: "bug"
            href: "https://github.com/viash-io/viash/issues"
          - text: "Report a website issue"
            icon: "bug"
            href: "https://github.com/viash-io/viash_web/issues"
          # - text: "Quarto Discussions"
          #   icon: "chat-right-text"
          #   href: "https://github.com/quarto-dev/quarto-cli/discussions"
          # - text: "FAQ"
          #   icon: "question-circle"
          #   href:  documentation/faq/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: Quarto GitHub

  sidebar:
    - id: get-started
      title: "Get Started"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - documentation/get-started/index.qmd
        - text: "Tutorial: Hello, Quarto"
          href: documentation/get-started/hello/
        - text: "Tutorial: Computations"
          href: documentation/get-started/computations/
        - text: "Tutorial: Authoring"
          href: documentation/get-started/authoring/




    - id: guide
      collapse-level: 1
      contents:
        - text: "Guide"
          href: documentation/guide/index.qmd
        - section: "Viash Component"
          contents:
            - section: "Creation"
              contents:
                - documentation/guide/component/creation/native.qmd
                - documentation/guide/component/creation/docker.qmd
                - documentation/guide/component/creation/nextflow.qmd
        - section: "Building Block"
          contents:
            - section: "Native Executable"
            - section: "Docker Backend Executable"
            - section: "Nextflow Module"
              contents:
                - documentation/guide/building-block/nextflow/building-running.qmd
        - section: "Data Workflow"
          contents:
            - section: "Scripted Pipeline"
            - section: "Nextflow Pipeline"
              contents:
                - documentation/guide/data-workflow/nextflow-pipeline/pipeline-basics.qmd
                - documentation/guide/data-workflow/nextflow-pipeline/pipeline-advanced.qmd
        - section: "Project"
          contents:
            - section: "Setup"
            - section: "Customizing"


        - section: "No Category"
          contents:
          - documentation/guide/temp/docker-build-run.qmd
          - documentation/guide/temp/docker-volume-creation.qmd
          - documentation/guide/temp/language-csharp.qmd
          - documentation/guide/temp/language-r.qmd
          - documentation/guide/temp/namespace.qmd
          - documentation/guide/temp/project-ci-cd.qmd
          - documentation/guide/temp/project-unit-testing.qmd
          - documentation/guide/temp/docker-print-config.qmd
          - documentation/guide/temp/external-resources.qmd
          - documentation/guide/temp/language-javascript.qmd
          - documentation/guide/temp/language-scala.qmd
          - documentation/guide/temp/project-customizing.qmd
          - documentation/guide/temp/scripted-pipeline.qmd
          - documentation/guide/temp/docker-setup-strategies.qmd
          - documentation/guide/temp/language-bash.qmd
          - documentation/guide/temp/language-python.qmd
          - documentation/guide/temp/migrating-from-native.qmd
          - documentation/guide/temp/project-build-run.qmd
          - documentation/guide/temp/project-setup.qmd
          - documentation/guide/temp/unit-testing.qmd











    - id: reference
      title: "API"
      contents:
        - text: "API"
          href: documentation/reference/index.qmd
        - section: "Formats"
          contents:
            - text: "HTML"
              href: documentation/reference/formats/html.qmd
            - text: "PDF"
              href: documentation/reference/formats/pdf.qmd
            - text: "MS Word"
              href: documentation/reference/formats/docx.qmd
            - text: "OpenOffice"
              href: documentation/reference/formats/odt.qmd
            - text: "ePub"
              href: documentation/reference/formats/epub.qmd
            - section: "Presentations"
              contents:
                - text: "Revealjs"
                  href: documentation/reference/formats/presentations/revealjs.qmd
                - text: "PowerPoint"
                  href: documentation/reference/formats/presentations/pptx.qmd
                - text: "Beamer"
                  href: documentation/reference/formats/presentations/beamer.qmd
            - section: "Markdown"
              contents:
                - text: "GitHub"
                  href: documentation/reference/formats/markdown/gfm.qmd
                - text: "CommonMark"
                  href: documentation/reference/formats/markdown/commonmark.qmd
                - text: "Hugo"
                  href: documentation/reference/formats/markdown/hugo.qmd
                - text: "Markua"
                  href: documentation/reference/formats/markdown/markua.qmd
            - section: "Wikis"
              contents:
                - text: "MediaWiki"
                  href: documentation/reference/formats/wiki/mediawiki.qmd
                - text: "DokuWiki"
                  href: documentation/reference/formats/wiki/dokuwiki.qmd
                - text: "ZimWiki"
                  href: documentation/reference/formats/wiki/zimwiki.qmd
                - text: "Jira Wiki"
                  href: documentation/reference/formats/wiki/jira.qmd
                - text: "XWiki"
                  href: documentation/reference/formats/wiki/xwiki.qmd
            - section: "More Formats"
              contents:
                - text: "JATS"
                  href: documentation/reference/formats/jats.qmd
                - text: "Jupyter"
                  href: documentation/reference/formats/ipynb.qmd
                - text: "ConTeXt"
                  href: documentation/reference/formats/context.qmd
                - text: "RTF"
                  href: documentation/reference/formats/rtf.qmd
                - text: "reST"
                  href: documentation/reference/formats/rst.qmd
                - text: "AsciiDoc"
                  href: documentation/reference/formats/asciidoc.qmd
                - text: "Org-Mode"
                  href: documentation/reference/formats/org.qmd
                - text: "Muse"
                  href: documentation/reference/formats/muse.qmd
                - text: "GNU TexInfo"
                  href: documentation/reference/formats/texinfo.qmd
                - text: "Groff Man Page"
                  href: documentation/reference/formats/man.qmd
                - text: "Groff Manuscript"
                  href: documentation/reference/formats/ms.qmd
                - text: "Haddock markup"
                  href: documentation/reference/formats/haddock.qmd
                - text: "OPML"
                  href: documentation/reference/formats/opml.qmd
                - text: "Textile"
                  href: documentation/reference/formats/textile.qmd
                - text: "DocBook"
                  href: documentation/reference/formats/docbook.qmd
                - text: "InDesign"
                  href: documentation/reference/formats/icml.qmd
                - text: "TEI Simple"
                  href: documentation/reference/formats/tei.qmd
                - text: "FictionBook"
                  href: documentation/reference/formats/fb2.qmd
        - section: "Code Cells"
          contents:
            - text: "Jupyter"
              href: documentation/reference/cells/cells-jupyter.qmd
            - text: "Knitr"
              href: documentation/reference/cells/cells-knitr.qmd
            - text: "Observable"
              href: documentation/reference/cells/cells-ojs.qmd

bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    link-external-icon: false
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html

filters:
  - filters/include-files.lua
  - quarto

freeze: auto

