functionality:
  name: hello_world
  description: A minimal example component.
  arguments:
  - type: string
    name: --input
    default: "World"
  - type: string
    name: --id
    default: "hello_world"
  - type: file
    name: --output
    direction: output
    default: "output"
  resources:
  - type: csharp_script
    path: script.csx
platforms:
  - type: native
  - type: docker
    image: "dataintuitive/dotnet-script:1.2.1"
    setup:
      - type: apk
        packages: [ bash ]
  - type: nextflow
    variant: vdsl3