data:
- description: "A list of platforms to generate target artifacts for.\n\n * [Native](/reference/config/platforms/native/#)\n\
    \ * [Docker](/reference/config/platforms/docker/#)\n * [Nextflow VDSL3](/reference/config/platforms/nextflow/#)\n"
  example:
  - example: "platforms:\n  - type: docker\n    image: \"bash:4.0\"\n  - type: native\n\
      \  - type: nextflow\n    directives:\n      label: [lowcpu, midmem]\n"
    format: yaml
  hierarchy:
  - io.viash.platforms.Platform
  name: __this__
  type: Platform
title: Platform
topic: platforms
