functionality:
  name: example_csharp
  description: A minimal example component.
  arguments:
    - type: file
      name: --input
      example: file.txt
      required: true
    - type: file
      name: --output
      direction: output
      example: output.txt
      required: true
  resources:
    - type: csharp_script
      path: script.csx
  # test disabled for now
  # test_resources:
  #   - type: bash_script
  #     path: test.sh
platforms:
  - type: docker
    image: "dataintuitive/dotnet-script:1.2.1"
    setup:
      - type: apk
        packages: [ bash ]
  - type: native
  - type: nextflow