functionality:
  name: add
  namespace: math
  arguments:
  - type: integer
    name: --num1
    default: 1
  - type: integer
    name: --num2
    default: 1
  resources:
  - type: bash_script
    path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
platforms:
  - type: native