functionality:
  name: remove_comments
  description: My first Nextflow pipeline module
  namespace: example
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      required: true
      direction: output
    - type: string
      name: --id
      default: "remove_comments"
  resources:
  - type: bash_script
    path: ./script.sh
platforms:
  - type: docker
    image: ubuntu:20.04
  - type: nextflow
    variant: vdsl3