functionality:
  name: hello_world
  description: A minimal example component.
  arguments:
  - type: string
    name: --input
    default: "World"
  resources:
  - type: r_script
    path: script.R
platforms:
  - type: native
  - type: docker
    image: "rocker/tidyverse:4.0.4"
  - type: nextflow