functionality:
  name: hello_viash
  description: A minimal example component.
  arguments:
  - type: string
    name: --input
    default: "Viash"
  resources:
  - type: csharp_script
    path: script.csx
platforms:
  - type: native