functionality:
  name: hello_viash
  description: A minimal example component.
  arguments:
  - type: string
    name: --input
    default: "Viash"
  resources:
  - type: scala_script
    path: script.scala
platforms:
  - type: native
  - type: docker
    image: hseeberger/scala-sbt