data:
- description: 'Running a Viash component on a native platform means that the script
    will be executed in your current environment.

    Any dependencies are assumed to have been installed by the user, so the native
    platform is meant for developers (who know what they''re doing) or for simple
    bash scripts (which have no extra dependencies).

    '
  hierarchy:
  - io.viash.platforms.NativePlatform
  - io.viash.platforms.Platform
  name: __this__
  type: NativePlatform
- description: 'As with all platforms, you can give a platform a different name. By
    specifying `id: foo`, you can target this platform (only) by specifying `-p foo`
    in any of the Viash commands.'
  example:
  - example: 'id: foo'
    format: yaml
  name: id
  type: String
- description: Specifies the type of the platform.
  name: type
  type: String
title: Native Platform
topic: platforms
