data:
- description: Specify which apk packages should be available in order to run the
    component.
  example:
  - example: "setup:\n  - type: apk\n    packages: [ sl ]\n"
    format: yaml
  hierarchy:
  - io.viash.platforms.requirements.ApkRequirements
  - io.viash.platforms.requirements.Requirements
  name: __this__
  type: ApkRequirements
- description: Specifies which packages to install.
  example:
  - example: 'packages: [ sl ]'
    format: yaml
  name: packages
  type: OneOrMore of String
- description: Specifies the type of the requirement specification.
  name: type
  type: String
title: Apk Requirements
topic: requirements
