data:
- description: Specify which apt packages should be available in order to run the
    component.
  example:
  - example: "setup:\n  - type: apt\n    packages: [ sl ]\n"
    format: yaml
  hierarchy:
  - io.viash.platforms.requirements.AptRequirements
  - io.viash.platforms.requirements.Requirements
  name: __this__
  type: AptRequirements
- description: 'If `false`, the Debian frontend is set to non-interactive (recommended).
    Default: false.'
  name: interactive
  type: Boolean
- description: Specifies which packages to install.
  example:
  - example: 'packages: [ sl ]'
    format: yaml
  name: packages
  type: OneOrMore of String
- description: Specifies the type of the requirement specification.
  name: type
  type: String
title: Apt Requirements
topic: requirements
