functionality:
  name: take_column
  namespace: nextflow_modules
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      required: true
      direction: output
    - name: "--column"
      type: integer
      required: false
      default: 2
    - type: string
      name: --id
      default: "take_column"
  resources:
  - type: python_script
    path: ./script.py
platforms:
  - type: nextflow
    variant: vdsl3
    directives:
      container: amancevice/pandas:slim