structure:
  'config/config': ./index
  'config/project': ../project/index
  'config/info': ./info
  'config/environmentVariables': ./environmentVariables

  'functionality/functionality': ./functionality/index
  'functionality/author': ./functionality/author
  'functionality/computationalRequirements': ./functionality/computationalRequirements
  'functionality/argumentGroup': ./functionality/argumentGroup

  'platforms/platform': ./platforms/index
  'platforms/nativePlatform': ./platforms/native/index
  'platforms/dockerPlatform': ./platforms/docker/index
  'platforms/nextflowVdsl3Platform': ./platforms/nextflow/index
  'platforms/nextflowLegacyPlatform': ./platforms/nextflowLegacy/index

  'arguments/argument': ./functionality/arguments/index
  'arguments/boolean_false': ./functionality/arguments/boolean_false
  'arguments/boolean': ./functionality/arguments/boolean
  'arguments/boolean_true': ./functionality/arguments/boolean_true
  'arguments/double': ./functionality/arguments/double
  'arguments/file': ./functionality/arguments/file
  'arguments/integer': ./functionality/arguments/integer
  'arguments/long': ./functionality/arguments/long
  'arguments/string': ./functionality/arguments/string
  
  'requirements/requirements': ./platforms/docker/setup/index
  'requirements/apkRequirements': ./platforms/docker/setup/apkRequirements
  'requirements/aptRequirements': ./platforms/docker/setup/aptRequirements
  'requirements/dockerRequirements': ./platforms/docker/setup/dockerRequirements
  'requirements/javascriptRequirements': ./platforms/docker/setup/javascriptRequirements
  'requirements/pythonRequirements': ./platforms/docker/setup/pythonRequirements
  'requirements/rRequirements': ./platforms/docker/setup/rRequirements
  'requirements/rubyRequirements': ./platforms/docker/setup/rubyRequirements
  'requirements/yumRequirements': ./platforms/docker/setup/yumRequirements

  'resources/resource': ./functionality/resources/index
  'resources/cSharpScript': ./functionality/resources/cSharpScript
  'resources/pythonScript': ./functionality/resources/pythonScript
  'resources/plainFile': ./functionality/resources/plainFile
  'resources/bashScript': ./functionality/resources/bashScript
  'resources/scalaScript': ./functionality/resources/scalaScript
  'resources/nextflowScript': ./functionality/resources/nextflowScript
  'resources/rScript': ./functionality/resources/rScript
  'resources/executable': ./functionality/resources/executable
  'resources/javaScriptScript': ./functionality/resources/javaScriptScript

  'nextflowParameters/nextflowDirectives': ./platforms/nextflow/directives
  'nextflowParameters/nextflowAuto': ./platforms/nextflow/auto
  'nextflowParameters/nextflowConfig': ./platforms/nextflow/config

order:
  'config/config': 20
  'config/project': 30

  'functionality/functionality': 10
  'platforms/platform': 20
  'config/info': 30
  
  'platforms/nativePlatform': 10
  'platforms/dockerPlatform': 20
  'platforms/nextflowVdsl3Platform': 30
  'platforms/nextflowLegacyPlatform': 40

keywords:
  mykeyword: /reference/config.html
  namespace: /guide/project/structure.html#grouping-components-in-namespaces
  config_mod: /reference/config_mods/#
  docker_setup_strategy: /guide/component/add-dependencies.html#step-3-rebuild-docker-image
  docker_registry: /reference/config/platforms/docker/#registry
  docker_tag: /reference/config/platforms/docker/#tag
  resources: /reference/config/functionality/resources/#
  unit_testing: /guide/component/unit-testing.html
  scripting_languages: /guide/component/create-component.html#create-a-script
  argument_groups: /reference/config/functionality/#argument_groups
  author: /reference/config/functionality/author.html
  computational_requirements: /reference/config/functionality/computationalRequirements.html
  apk_req: /reference/config/platforms/docker/setup/apkRequirements.html
  apt_req: /reference/config/platforms/docker/setup/aptRequirements.html
  docker_req: /reference/config/platforms/docker/setup/dockerRequirements.html
  javascript_req: /reference/config/platforms/docker/setup/javascriptRequirements.html
  python_req: /reference/config/platforms/docker/setup/pythonRequirements.html
  r_req: /reference/config/platforms/docker/setup/rRequirements.html
  ruby_req: /reference/config/platforms/docker/setup/rubyRequirements.html
  yum_req: /reference/config/platforms/docker/setup/yumRequirements.html
  argument: /reference/config/functionality/arguments/#
  arg_string: /reference/config/functionality/arguments/string.html
  arg_file: /reference/config/functionality/arguments/file.html
  arg_integer: /reference/config/functionality/arguments/integer.html
  arg_double: /reference/config/functionality/arguments/double.html
  arg_float: /reference/config/functionality/arguments/float.html
  arg_boolean: /reference/config/functionality/arguments/boolean.html
  arg_boolean_true: /reference/config/functionality/arguments/boolean_true.html
  arg_boolean_false: /reference/config/functionality/arguments/boolean_false.html
  functionality: /reference/config/functionality/#
  platform_native: /reference/config/platforms/native/#
  platform_docker: /reference/config/platforms/docker/#
  platform_nextflow: /reference/config/platforms/nextflow/#
  nextflow_directives: /reference/config/platforms/nextflow/directives.html
  nextflow_auto: /reference/config/platforms/nextflow/auto.html
  nextflow_config: /reference/config/platforms/nextflow/config.html