structure:
  './config': ./index.qmd
  './functionality': ./functionality/index.qmd

  'platforms/nativePlatform': ./platforms/native/index.qmd
  'platforms/dockerPlatform': ./platforms/docker/index.qmd
  'platforms/nextflowVdsl3Platform': ./platforms/nextflow/index.qmd
  'platforms/nextflowLegacyPlatform': ./platforms/nextflowLegacy/index.qmd

  'arguments/argument': ./functionality/arguments/index.qmd
  'arguments/boolean_false': ./functionality/arguments/boolean_false.qmd
  'arguments/boolean': ./functionality/arguments/boolean.qmd
  'arguments/boolean_true': ./functionality/arguments/boolean_true.qmd
  'arguments/double': ./functionality/arguments/double.qmd
  'arguments/file': ./functionality/arguments/file.qmd
  'arguments/integer': ./functionality/arguments/integer.qmd
  'arguments/long': ./functionality/arguments/long.qmd
  'arguments/string': ./functionality/arguments/string.qmd
  
  'requirements/requirements': ./platforms/docker/setup/index.qmd
  'requirements/apkRequirements': ./platforms/docker/setup/apkRequirements.qmd
  'requirements/aptRequirements': ./platforms/docker/setup/aptRequirements.qmd
  'requirements/dockerRequirements': ./platforms/docker/setup/dockerRequirements.qmd
  'requirements/javascriptRequirements': ./platforms/docker/setup/javascriptRequirements.qmd
  'requirements/pythonRequirements': ./platforms/docker/setup/pythonRequirements.qmd
  'requirements/rRequirements': ./platforms/docker/setup/rRequirements.qmd
  'requirements/rubyRequirements': ./platforms/docker/setup/rubyRequirements.qmd
  'requirements/yumRequirements': ./platforms/docker/setup/yumRequirements.qmd

  'resources/resource': ./functionality/resources/index.qmd
  'resources/cSharpScript': ./functionality/resources/cSharpScript.qmd
  'resources/pythonScript': ./functionality/resources/pythonScript.qmd
  'resources/plainFile': ./functionality/resources/plainFile.qmd
  'resources/bashScript': ./functionality/resources/bashScript.qmd
  'resources/scalaScript': ./functionality/resources/scalaScript.qmd
  'resources/nextflowScript': ./functionality/resources/nextflowScript.qmd
  'resources/rScript': ./functionality/resources/rScript.qmd
  'resources/executable': ./functionality/resources/executable.qmd
  'resources/javaScriptScript': ./functionality/resources/javaScriptScript.qmd

  './project': ../project/index.qmd
  './nextflowDirectives': ./platforms/nextflow/directives.qmd

order:
  './config': 20
  './project': 30
  'platforms/nativePlatform': 10
  'platforms/dockerPlatform': 20
  'platforms/nextflowVdsl3Platform': 30
  'platforms/nextflowLegacyPlatform': 40

keywords:
  mykeyword: /reference/config.html
  namespace: /guide/project/getting-started.html#grouping-components-in-namespaces
  config_mod: /reference/config_mods/#
  docker_setup_strategy: /guide/component/add-dependencies.html#step-3-rebuild-docker-image
  docker_registry: /reference/config/platforms/docker/#registry
  docker_tag: /reference/config/platforms/docker/#tag
  resources: /reference/config/functionality/resources/#
  unit_testing: /guide/component/unit-testing.html
  scripting_languages: /guide/component/create-component.html#create-a-script
  argument_groups: /reference/config/functionality/#argument_groups
  apk_req: /reference/config/platforms/docker/setup/apkRequirements.html
  apt_req: /reference/config/platforms/docker/setup/aptRequirements.html
  docker_req: /reference/config/platforms/docker/setup/dockerRequirements.html
  javascript_req: /reference/config/platforms/docker/setup/javascriptRequirements.html
  python_req: /reference/config/platforms/docker/setup/pythonRequirements.html
  r_req: /reference/config/platforms/docker/setup/rRequirements.html
  ruby_req: /reference/config/platforms/docker/setup/rubyRequirements.html
  yum_req: /reference/config/platforms/docker/setup/yumRequirements.html
  arg_string: /reference/config/functionality/arguments/string.html
  arg_file: /reference/config/functionality/arguments/file.html
  arg_integer: /reference/config/functionality/arguments/integer.html
  arg_double: /reference/config/functionality/arguments/double.html
  arg_float: /reference/config/functionality/arguments/float.html
  arg_boolean: /reference/config/functionality/arguments/boolean.html
  arg_boolean_true: /reference/config/functionality/arguments/boolean_true.html
  arg_boolean_false: /reference/config/functionality/arguments/boolean_false.html
  functionality: /reference/config/functionality/index.html
  platform_native: /reference/config/platforms/native/index.html
  platform_docker: /reference/config/platforms/docker/index.html
  platform_nextflow: /reference/config/platforms/nextflow/index.html
  nextflow_directives: /reference/config/platforms/nextflow/directives.html