structure:

  'arguments/boolean_false': ./functionality/arguments/boolean_false.qmd
  'arguments/boolean': ./functionality/arguments/boolean.qmd
  'arguments/boolean_true': ./functionality/arguments/boolean_true.qmd
  'arguments/double': ./functionality/arguments/double.qmd
  'arguments/file': ./functionality/arguments/file.qmd
  'arguments/integer': ./functionality/arguments/integer.qmd
  'arguments/long': ./functionality/arguments/long.qmd
  'arguments/string': ./functionality/arguments/string.qmd
  'functionality': ./functionality/index.qmd
  'config': ./index.qmd
  'platforms/DockerPlatform': ./platforms/docker/index.qmd
  'setup/apkRequirements': ./platforms/docker/setup/apkRequirements.qmd
  'setup/aptRequirements': ./platforms/docker/setup/aptRequirements.qmd
  'setup/dockerRequirements': ./platforms/docker/setup/dockerRequirements.qmd
  'requirements': ./platforms/docker/setup/index.qmd
  'setup/javascriptRequirements': ./platforms/docker/setup/javascriptRequirements.qmd
  'setup/pythonRequirements': ./platforms/docker/setup/pythonRequirements.qmd
  'setup/rRequirements': ./platforms/docker/setup/rRequirements.qmd
  'setup/rubyRequirements': ./platforms/docker/setup/rubyRequirements.qmd
  'setup/yumRequirements': ./platforms/docker/setup/yumRequirements.qmd
  'platforms/NativePlatform': ./platforms/native/index.qmd
  'platforms/NextflowVdsl3Platform': ./platforms/nextflow/index.qmd
  'platforms/NextflowLegacyPlatform': ./platforms/nextflow/NextflowLegacyPlatform.qmd

keywords:
  mykeyword: /reference/config.html
  namespace: /guide/component/namespaces.html
  config_mod: /reference/config/config_mods/#
  docker_setup_strategy: /guide/building-block/docker/setup-strategies.html
  docker_registry: /reference/config/platforms/docker/#registry
  docker_tag: /reference/config/platforms/docker/#tag
  resources: #
  unit_testing: /guide/component/unit-testing.html
  scripting_languages: /guide/component/languages.html
  argument_groups: /reference/config/functionality/#argument_groups
  apk_req: /reference/config/platforms/docker/setup/#apk-requirements
  apt_req: /reference/config/platforms/docker/setup/#apt-requirements
  docker_req: /reference/config/platforms/docker/setup/#docker-requirements
  javascript_req: /reference/config/platforms/docker/setup/#javascript-requirements
  python_req: /reference/config/platforms/docker/setup/#python-requirements
  r_req: /reference/config/platforms/docker/setup/#r-requirements
  ruby_req: /reference/config/platforms/docker/setup/#ruby-requirements
  yum_req: /reference/config/platforms/docker/setup/#yum-requirements
  arg_string: /reference/config/functionality/arguments/string.html
  arg_file: /reference/config/functionality/arguments/file.html
  arg_integer: /reference/config/functionality/arguments/integer.html
  arg_double: /reference/config/functionality/arguments/double.html
  arg_float: /reference/config/functionality/arguments/float.html
  arg_boolean: /reference/config/functionality/arguments/boolean.html
  arg_boolean_true: /reference/config/functionality/arguments/boolean_true.html
  arg_boolean_false: /reference/config/functionality/arguments/boolean_false.html
  functionality: /reference/config/functionality/index.html
  platform_native: /reference/config/platforms/native/index.html
  platform_docker: /reference/config/platforms/docker/index.html
  platform_nextflow: /reference/config/platforms/nextflow/index.html