functionality:
  name: hello_world
  description: A minimal example component.
  arguments:
  - type: string
    name: --input
    default: "World"
  resources:
  - type: csharp_script
    path: script.csx
platforms:
  - type: native
  - type: docker
    image: "dataintuitive/dotnet-script:1.2.1"
    setup:
      - type: apk
        packages: [ bash ]
  - type: nextflow