data:
- description: Automated processing flags which can be toggled on or off.
  hierarchy:
  - io.viash.platforms.nextflow.NextflowAuto
  name: __this__
  type: NextflowAuto
- description: 'If `true`, an input tuple only containing only a single File (e.g.
    `["foo", file("in.h5ad")]`) is automatically transformed to a map (i.e. `["foo",
    [ input: file("in.h5ad") ] ]`).


    Default: `true`.

    '
  name: simplifyInput
  type: Boolean
- description: 'If `true`, an output tuple containing a map with a File (e.g. `["foo",
    [ output: file("out.h5ad") ] ]`) is automatically transformed to a map (i.e. `["foo",
    file("out.h5ad")]`).


    Default: `true`.

    '
  name: simplifyOutput
  type: Boolean
- description: 'If `true`, the module''s outputs are automatically published to `params.publishDir`.

    Will throw an error if `params.publishDir` is not defined.


    Default: `false`.

    '
  name: publish
  type: Boolean
- description: 'If `true`, the module''s transcripts from `work/` are automatically
    published to `params.transcriptDir`.

    If not defined, `params.publishDir + "/_transcripts"` will be used.

    Will throw an error if neither are defined.


    Default: `false`.

    '
  name: transcript
  type: Boolean
title: Nextflow Auto
topic: nextflowParameters
