data:
- description: Allows tweaking how the Nextflow Config file is generated.
  hierarchy:
  - io.viash.platforms.nextflow.NextflowConfig
  name: __this__
  type: NextflowConfig
- description: 'A series of default labels to specify memory and cpu constraints.


    The default memory labels are defined as "mem1gb", "mem2gb", "mem4gb", ... upto
    "mem512tb" and follows powers of 2.

    The default cpu labels are defined as "cpu1", "cpu2", "cpu5", "cpu10", ... upto
    "cpu1000" and follows a semi logarithmic scale (1, 2, 5 per decade).


    Conceptually it is possible for a Viash Config to overwrite the full labels parameter,
    however likely it is more efficient to add additional labels

    in the Viash Project with a config mod.

    '
  example:
  - description: Replace the default labels with a different set of labels
    example: "labels:\n  lowmem: \"memory = 4.GB\"\n  lowcpu: \"cpus = 4\"\n  midmem:\
      \ \"memory = 25.GB\"\n  midcpu: \"cpus = 10\"\n  highmem: \"memory = 50.GB\"\
      \n  highcpu: \"cpus = 20\"\n  vhighmem: \"memory = 100.GB\"\n  vhighcpu: \"\
      cpus = 40\"\n"
    format: yaml
  - description: Add 'lowmem' and 'lowcpu' to the default labels by using a config
      mod
    example: -c '.platforms[.type == "nextflow"].config.labels.lowmem := "memory =
      4.GB";.platforms[.type == "nextflow"].config.labels.lowcpu := "cpus = 4"'
    format: viash_config_mod
  - description: Add 'lowmem' and 'lowcpu' to the default labels by using the Viash
      Project file
    example: "config_mods: |\n  .platforms[.type == \"nextflow\"].config.labels.lowmem\
      \ := \"memory = 4.GB\"\n  .platforms[.type == \"nextflow\"].config.labels.lowcpu\
      \ := \"cpus = 4\"\n"
    format: viash_project_file
  - description: Replace the default labels with a different set of labels by using
      the Viash Project file
    example: "config_mods: |\n  .platforms[.type == \"nextflow\"].config.labels :=\
      \ { lowmem: \"memory = 4.GB\", lowcpu: \"cpus = 4\", midmem: \"memory = 25.GB\"\
      , midcpu: \"cpus = 10\", highmem: \"memory = 50.GB\", highcpu: \"cpus = 20\"\
      , vhighmem: \"memory = 100.GB\", vhighcpu: \"cpus = 40\" }\n"
    format: viash_project_file
  name: labels
  type: ListMap of String,String
title: Nextflow Config
topic: nextflowParameters
