data:
- description: Next-gen platform for generating NextFlow VDSL3 modules.
  hierarchy:
  - io.viash.platforms.NextflowVdsl3Platform
  - io.viash.platforms.NextflowPlatform
  - io.viash.platforms.Platform
  name: __this__
  title: Nextflow Vdsl3 Platform
  topic: platforms
  type: NextflowVdsl3Platform
- description: "Automated processing flags which can be toggled on or off:  \n\n|\
    \ Flag | Description | Default |\n|---|---------|----|\n| `simplifyInput` | If\
    \ `true`, an input tuple only containing only a single File (e.g. `[\"foo\", file(\"\
    in.h5ad\")]`) is automatically transformed to a map (i.e. `[\"foo\", [ input:\
    \ file(\"in.h5ad\") ] ]`). | `true` |\n| `simplifyOutput` | If `true`, an output\
    \ tuple containing a map with a File (e.g. `[\"foo\", [ output: file(\"out.h5ad\"\
    ) ] ]`) is automatically transformed to a map (i.e. `[\"foo\", file(\"out.h5ad\"\
    )]`). | `true` |\n| `transcript` | If `true`, the module's transcripts from `work/`\
    \ are automatically published to `params.transcriptDir`. If not defined, `params.publishDir\
    \ + \"/_transcripts\"` will be used. Will throw an error if neither are defined.\
    \ | `false` |\n| `publish` | If `true`, the module's outputs are automatically\
    \ published to `params.publishDir`.  Will throw an error if `params.publishDir`\
    \ is not defined. | `false` |\n\n"
  example:
  - example: "auto:\n    publish: true"
    format: yaml
  name: auto
  title: Nextflow Vdsl3 Platform
  topic: platforms
  type: NextflowAuto
- description: Specifies the Docker platform id to be used to run Nextflow.
  name: container
  title: Nextflow Vdsl3 Platform
  topic: platforms
  type: String
- description: Whether or not to print debug messages.
  name: debug
  title: Nextflow Vdsl3 Platform
  topic: platforms
  type: Boolean
- description: "Directives are optional settings that affect the execution of the\
    \ process. These mostly match up with the Nextflow counterparts that are linked\
    \ below:  \n\n - [`accelerator`](https://www.nextflow.io/docs/latest/process.html#accelerator)\n\
    \ - [`afterScript`](https://www.nextflow.io/docs/latest/process.html#afterscript)\n\
    \ - [`beforeScript`](https://www.nextflow.io/docs/latest/process.html#beforeScript)\n\
    \ - [`cache`](https://www.nextflow.io/docs/latest/process.html#cache)\n - [`conda`](https://www.nextflow.io/docs/latest/process.html#conda)\n\
    \ - [`container`](https://www.nextflow.io/docs/latest/process.html#container)\n\
    \ - [`containerOptions`](https://www.nextflow.io/docs/latest/process.html#containeroptions)\n\
    \ - [`cpus`](https://www.nextflow.io/docs/latest/process.html#cpus)\n - [`disk`](https://www.nextflow.io/docs/latest/process.html#disk)\n\
    \ - [`echo`](https://www.nextflow.io/docs/latest/process.html#echo)\n - [`errorStrategy`](https://www.nextflow.io/docs/latest/process.html#errorstrategy)\n\
    \ - [`executor`](https://www.nextflow.io/docs/latest/process.html#executor)\n\
    \ - [`machineType`](https://www.nextflow.io/docs/latest/process.html#machinetype)\n\
    \ - [`maxErrors`](https://www.nextflow.io/docs/latest/process.html#maxerrors)\n\
    \ - [`maxForks`](https://www.nextflow.io/docs/latest/process.html#maxforks)\n\
    \ - [`maxRetries`](https://www.nextflow.io/docs/latest/process.html#maxretries)\n\
    \ - [`memory`](https://www.nextflow.io/docs/latest/process.html#memory)\n - [`module`](https://www.nextflow.io/docs/latest/process.html#module)\n\
    \ - [`penv`](https://www.nextflow.io/docs/latest/process.html#penv)\n - [`publishDir`](https://www.nextflow.io/docs/latest/process.html#publishdir)\n\
    \ - [`queue`](https://www.nextflow.io/docs/latest/process.html#queue)\n - [`scratch`](https://www.nextflow.io/docs/latest/process.html#scratch)\n\
    \ - [`storeDir`](https://www.nextflow.io/docs/latest/process.html#storeDir)\n\
    \ - [`stageInMode`](https://www.nextflow.io/docs/latest/process.html#stageinmode)\n\
    \ - [`stageOutMode`](https://www.nextflow.io/docs/latest/process.html#stageoutmode)\n\
    \ - [`tag`](https://www.nextflow.io/docs/latest/process.html#tag)\n - [`time`](https://www.nextflow.io/docs/latest/process.html#time)"
  example:
  - example: "directives:\n    container: rocker/r-ver:4.1\n    label: highcpu\n \
      \   cpus: 4\n    memory: 16 GB"
    format: yaml
  name: directives
  title: Nextflow Vdsl3 Platform
  topic: platforms
  type: NextflowDirectives
- description: Every platform can be given a specific id that can later be referred
    to explicitly when running or building the Viash component.
  example:
  - example: 'id: foo'
    format: yaml
  name: id
  title: Nextflow Vdsl3 Platform
  topic: platforms
  type: String
- description: Specifies the type of the platform.
  name: type
  title: Nextflow Vdsl3 Platform
  topic: platforms
  type: String
pageTitle: Nextflow Vdsl3 Platform
