functionality:
  name: hello_viash
  description: A minimal example component.
  arguments:
  - type: string
    name: --input
    default: "Viash"
  resources:
  - type: javascript_script
    path: script.js
platforms:
  - type: native
  - type: docker
    image: node:15-buster