functionality:
  name: hello_world
  description: A minimal example component.
  arguments:
  - type: string
    name: --input
    default: "World"
  resources:
  - type: scala_script
    path: script.scala
platforms:
  - type: native
  - type: docker
    image: hseeberger/scala-sbt
  - type: nextflow