data:
- description: Author metadata.
  example:
  - example: "name: Jane Doe\nrole: [author, maintainer]\nemail: jane@doe.com\ninfo:\n\
      \  github: janedoe\n  twitter: janedoe\n  orcid: XXAABBCCXX\n  groups: [ one,\
      \ two, three ]\n"
    format: yaml
  hierarchy:
  - io.viash.functionality.Author
  name: __this__
  since: Viash 0.3.2
  type: Author
- description: Full name of the author, usually in the name of FirstName MiddleName
    LastName.
  name: name
  type: String
- description: E-mail of the author.
  name: email
  type: Option of String
- description: 'Structured information. Can be any shape: a string, vector, map or
    even nested map.'
  name: info
  since: Viash 0.7.4
  type: Json
- description: 'Role of the author. Suggested items:


    * `"author"`: Authors who have made substantial contributions to the component.

    * `"maintainer"`: The maintainer of the component.

    * `"contributor"`: Authors who have made smaller contributions (such as code patches
    etc.).

    '
  name: roles
  type: OneOrMore of String
- deprecated:
    deprecation: 0.7.4
    message: Use `info` instead.
    removal: 0.8.0
  description: Author properties. Must be a map of strings.
  name: props
  type: Map of String,String
title: Author
topic: functionality
