data:
- description: Computational requirements related to running the component.
  hierarchy:
  - io.viash.functionality.ComputationalRequirements
  name: __this__
  since: Viash 0.6.0
  type: ComputationalRequirements
- name: n_proc
  removed:
    deprecation: 0.6.1
    message: Use `cpus` instead.
    removal: 0.7.0
  type: Option of Int
- description: The maximum number of (logical) cpus a component is allowed to use.
  example:
  - example: 'cpus: 10'
    format: yaml
  name: cpus
  type: Option of Int
- description: A list of commands which should be present on the system for the script
    to function.
  example:
  - example: 'commands: [ which, bash, awk, date, grep, egrep, ps, sed, tail, tee
      ]'
    format: yaml
  name: commands
  type: List of String
- description: The maximum amount of memory a component is allowed to allocate. Unit
    must be one of B, KB, MB, GB, TB or PB.
  example:
  - example: 'memory: 10GB'
    format: yaml
  name: memory
  type: Option of String
title: Computational Requirements
topic: functionality
